version: "3.8"
services:
  postgresDb:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sport-booking
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"