version: "3.8"
networks:
  sport_booking_prod_network:

services:

  postgresDb_prod:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    container_name: sport_booking_db_prod
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      sport_booking_prod_network:

  sport_booking_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: sport_booking_prod
    container_name: sport_booking_api_prod
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
      - POSTGRES_HOST=sport_booking_db_prod
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgresDb_prod
    volumes:
      - ./src:/app/src
    networks:
      sport_booking_prod_network: